### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by UrK** [CyberSource/cybersource-ios-sdk#5]
Hi
The library is currently built without Bitcode support introduced more than a year ago by Apple.
This prevents us from delivering our application with this feature also.
When will the library support Bitcode?

**Comment by AnneTheAgile** [comment]
This seems more urgent because it appears without bitcode compilation, Apple xcode 9 no longer allows creation of dsym debugging symbol files.

**Comment by ZezhongLi** [comment]
The new release 1.0.2 has added bitcode support.
